services:
  dev-web:
    build:
      context: ./docker
      network: host
    container_name: dev-web-01
    ports:
      - "2201:22"
      - "8080:8080"

  dev-db:
    build:
      context: ./docker
      network: host
    container_name: dev-db-01
    ports:
      - "2202:22"

  staging-web:
    build:
      context: ./docker
      network: host
    container_name: staging-web-01
    ports:
      - "2211:22"
      - "8081:8080"

  staging-db:
    build:
      context: ./docker
      network: host
    container_name: staging-db-01
    ports:
      - "2212:22"

  prod-web:
    build:
      context: ./docker
      network: host
    container_name: prod-web-01
    ports:
      - "2221:22"
      - "8082:80"

  prod-db:
    build:
      context: ./docker
      network: host
    container_name: prod-db-01
    ports:
      - "2223:22"
