services:
  dev-web:
    build: ./docker
    container_name: dev-web-01
    ports:
      - "2201:22"

  dev-db:
    build: ./docker
    container_name: dev-db-01
    ports:
      - "2202:22"

  staging-web:
    build: ./docker
    container_name: staging-web-01
    ports:
      - "2211:22"

  staging-db:
    build: ./docker
    container_name: staging-db-01
    ports:
      - "2212:22"

  prod-web:
    build: ./docker
    container_name: prod-web-01
    ports:
      - "2221:22"

  prod-db:
    build: ./docker
    container_name: prod-db-01
    ports:
      - "2223:22"
