[webservers]                                                                                                                                                                                                                                               
  prod-web-01 ansible_host=localhost ansible_port=2221
[databases]                                 
  prod-db-01 ansible_host=localhost ansible_port=2223

[all:children]                                                                                                                                                                                                                                             
 webservers
 databases