[webservers]
  staging-web-01 ansible_host=localhost ansible_port=2211                                                                                                                                                                                                    
                                                         
[databases]
  staging-db-01 ansible_host=localhost ansible_port=2212

[all:children]                              
  webservers                              
  databases